package dev.vayou.core.ui.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
class VayouColors(
    val accent: Color,
    val folderColor: Color,
    val accentOnBackground: Color,
    val onAccent: Color,
    val accentContainer: Color,
    val onAccentContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val outline: Color,
    val outlineVariant: Color,
    val divider: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val scrim: Color,
    val disabled: Color,
    val onDisabled: Color,
)

val VayouLightColors = VayouColors(
    accent = Color(0xFFFFB300),
    folderColor = Color(0xFFFFB300),
    accentOnBackground = Color(0xFF6B7280),
    onAccent = Color(0xFF1A1A1A),
    accentContainer = Color(0xFFF0F0F0),
    onAccentContainer = Color(0xFF1A1C20),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF1A1C20),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF1A1C20),
    surfaceVariant = Color(0xFFDEE3EB),
    onSurfaceVariant = Color(0xFF49454E),
    surfaceContainer = Color(0xFFF2F2F2),
    surfaceContainerHigh = Color(0xFFF5F5F5),
    surfaceContainerHighest = Color(0xFFE8E8E8),
    surfaceDim = Color(0xFFD9DADF),
    surfaceBright = Color(0xFFFFFFFF),
    outline = Color(0xFF72777F),
    outlineVariant = Color(0xFFC2C7CF),
    divider = Color(0xFFC2C7CF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    inverseSurface = Color(0xFF2F3033),
    inverseOnSurface = Color(0xFFF1F0F4),
    scrim = Color(0xFF000000),
    disabled = Color(0xFFC2C7CF),
    onDisabled = Color(0xFF72777F),
)

val VayouDarkColors = VayouColors(
    accent = Color(0xFFFFB300),
    folderColor = Color(0xFFFFB300),
    accentOnBackground = Color(0xFFFFB300),
    onAccent = Color(0xFF1A1A1A),
    accentContainer = Color(0xFF2C2C2C),
    onAccentContainer = Color(0xFFF1F1F1),
    background = Color(0xFF0E0E0E),
    onBackground = Color(0xFFF1F1F1),
    surface = Color(0xFF0E0E0E),
    onSurface = Color(0xFFF1F1F1),
    surfaceVariant = Color(0xFF2E2E2E),
    onSurfaceVariant = Color(0xFFCAC4C0),
    surfaceContainer = Color(0xFF1E1E1E),
    surfaceContainerHigh = Color(0xFF262626),
    surfaceContainerHighest = Color(0xFF2E2E2E),
    surfaceDim = Color(0xFF101316),
    surfaceBright = Color(0xFF36393E),
    outline = Color(0xFF8E8E8E),
    outlineVariant = Color(0xFF484848),
    divider = Color(0xFF484848),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    inverseSurface = Color(0xFFE2E2E6),
    inverseOnSurface = Color(0xFF2F3033),
    scrim = Color(0xFF000000),
    disabled = Color(0xFF484848),
    onDisabled = Color(0xFF8E8E8E),
)

val VayouPureBlackColors = VayouColors(
    accent = VayouDarkColors.accent,
    folderColor = VayouDarkColors.folderColor,
    accentOnBackground = VayouDarkColors.accentOnBackground,
    onAccent = VayouDarkColors.onAccent,
    accentContainer = VayouDarkColors.accentContainer,
    onAccentContainer = VayouDarkColors.onAccentContainer,
    background = Color(0xFF000000),
    onBackground = VayouDarkColors.onBackground,
    surface = Color(0xFF000000),
    onSurface = VayouDarkColors.onSurface,
    surfaceVariant = VayouDarkColors.surfaceVariant,
    onSurfaceVariant = VayouDarkColors.onSurfaceVariant,
    surfaceContainer = Color(0xFF161616),
    surfaceContainerHigh = Color(0xFF1C1C1C),
    surfaceContainerHighest = Color(0xFF222222),
    surfaceDim = Color(0xFF000000),
    surfaceBright = Color(0xFF2A2A2A),
    outline = VayouDarkColors.outline,
    outlineVariant = VayouDarkColors.outlineVariant,
    divider = VayouDarkColors.divider,
    error = VayouDarkColors.error,
    onError = VayouDarkColors.onError,
    errorContainer = VayouDarkColors.errorContainer,
    onErrorContainer = VayouDarkColors.onErrorContainer,
    inverseSurface = VayouDarkColors.inverseSurface,
    inverseOnSurface = VayouDarkColors.inverseOnSurface,
    scrim = VayouDarkColors.scrim,
    disabled = VayouDarkColors.disabled,
    onDisabled = VayouDarkColors.onDisabled,
)

val LocalVayouColors = staticCompositionLocalOf { VayouDarkColors }
